// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgQ6kovyUOenWcb9ZGpFafeUBMenHdgXQ',
    appId: '1:74033374187:web:f4f5a4035feeba194fefae',
    messagingSenderId: '74033374187',
    projectId: 'pulsebeat-8ec4e',
    authDomain: 'pulsebeat-8ec4e.firebaseapp.com',
    storageBucket: 'pulsebeat-8ec4e.firebasestorage.app',
    measurementId: 'G-0THZZ7PTVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH_iACE9_50pea9BqKcuEvix3jFgLD5Ok',
    appId: '1:74033374187:android:536c0693932c42434fefae',
    messagingSenderId: '74033374187',
    projectId: 'pulsebeat-8ec4e',
    storageBucket: 'pulsebeat-8ec4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5RCvmLDdlP00GmRQj5Aqpvz07vlGcZoE',
    appId: '1:74033374187:ios:9b2b0b8eaf75bdeb4fefae',
    messagingSenderId: '74033374187',
    projectId: 'pulsebeat-8ec4e',
    storageBucket: 'pulsebeat-8ec4e.firebasestorage.app',
    iosBundleId: 'com.example.shitySongsPlayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5RCvmLDdlP00GmRQj5Aqpvz07vlGcZoE',
    appId: '1:74033374187:ios:9b2b0b8eaf75bdeb4fefae',
    messagingSenderId: '74033374187',
    projectId: 'pulsebeat-8ec4e',
    storageBucket: 'pulsebeat-8ec4e.firebasestorage.app',
    iosBundleId: 'com.example.shitySongsPlayer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgQ6kovyUOenWcb9ZGpFafeUBMenHdgXQ',
    appId: '1:74033374187:web:a15d5a5722dc95664fefae',
    messagingSenderId: '74033374187',
    projectId: 'pulsebeat-8ec4e',
    authDomain: 'pulsebeat-8ec4e.firebaseapp.com',
    storageBucket: 'pulsebeat-8ec4e.firebasestorage.app',
    measurementId: 'G-2L6V9CGMH9',
  );
}
